version: 2

models:
      - name: stg_clients
        description: >
         Staging clients structure, cleansed and incrementlay loaded
        columns:
          - name: ADRESS_EMAIL
            data_type: varchar
            description: persinal email adress
          - name: COMPANY
            data_type: varchar
            description: COMPANY name of the client
          - name: CREDIT_CARD
            data_type: varchar
            description: CVV credit card number
          - name: FIRST_NAME
            data_type: varchar
            description: First name
          - name: ID
            data_type: varchar
            description: numeric id from CDC
            tests:
              - not_null
              - unique
          - name: LAST_NAME
            data_type: varchar
            description: Last name
          - name: NATION
            data_type: varchar
            description: Client's nation
          - name: PASSPORT_NUMBER
            data_type: varchar
            description: Client's Passport
          - name: PESEL
            data_type: varchar
            description: PESEL
          - name: PHONE_NUMBER
            data_type: varchar
            description: PHONE_NUMBER
          - name: OP
            data_type: varchar
            description: Type of registrated operation
          - name: TRANSACTION
            data_type: int
            description: DB transaction
          - name: TS_MS
            data_type: timestamp
            description: transaction timestamp in ms
          - name: added_at
            data_type: timestamp
            description: Streams transfer date
      
      - name: stg_clients_mails
        description: >
         Staging mails structure, cleansed and incrementlay loaded
        columns:
          - name: ADRESS_EMAIL
            data_type: varchar
            description: persinal email adress
            tests:
              - not_null
          - name: COMPANY
            data_type: varchar
            description: COMPANY name of the client
          - name: NATION
            data_type: varchar
            description: Client's nation
          - name: added_at
            data_type: timestamp
            description: Streams transfer date
          - name: rownum_id
            data_type: int
            description: Sequential rowid in RAW layer
            tests:
              - not_null
              - unique
              - relationships:
                  to: ref('raw_client')
                  field: rownum_id
